# Import Library
 - numpy as np

In [10]:
import numpy as np

In [11]:
one_d=np.array([1,2,3,4])
one_d

array([1, 2, 3, 4])

In [14]:
arr1=np.array([1,6,3,1])
type(arr1)

numpy.ndarray

In [28]:
# ndim = number of dimention  one D / Two D
arr1.ndim

1

In [21]:
two_d = np.array([[1,2,4,5],[6,7,8,9]])
print(two_d)

[[1 2 4 5]
 [6 7 8 9]]


In [20]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 1D array
print(two_d_array) #printing 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
two_d.ndim 


2

In [24]:
# Size of array   ----elements in array
two_d.size

8

In [26]:
# shape of array ---- order of array
two_d.shape

(2, 4)

In [27]:
# data_type of array
two_d.dtype

dtype('int32')