In [1]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr.ndim


2

In [5]:
arr.size

9

In [6]:
arr.shape

(3, 3)

In [13]:
arr1 = np.ones((2,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((4,5) , dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((2,4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False]])

In [31]:
np.zeros((2,4),dtype=str)

array([['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [32]:
food=np.array(["Samosa","Dall chana","kabbab"])
food


array(['Samosa', 'Dall chana', 'kabbab'], dtype='<U10')

In [33]:
food[1]

'Dall chana'

In [35]:
price=np.array([1,2,5,7,34,2,5])
price.mean()

8.0

### Linspace  
- specific interval between values

In [36]:
mm=np.linspace(1,10,5)
mm


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### We can specifiy our datatype

In [37]:
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [39]:
np.ones(5,dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array Functions

In [40]:
a=np.array([1,42,53,12,53,64,123,23.23,123,213])
a

array([  1.  ,  42.  ,  53.  ,  12.  ,  53.  ,  64.  , 123.  ,  23.23,
       123.  , 213.  ])

In [43]:
# sort an array:
a.sort()
a

array([  1.  ,  12.  ,  23.23,  42.  ,  53.  ,  53.  ,  64.  , 123.  ,
       123.  , 213.  ])

In [44]:
b=np.array([10.2,213,34,23,4234,435,234,234])
b

array([  10.2,  213. ,   34. ,   23. , 4234. ,  435. ,  234. ,  234. ])

In [46]:
c=np.concatenate((a,b))
c.sort()
c

array([1.000e+00, 1.020e+01, 1.200e+01, 2.300e+01, 2.323e+01, 3.400e+01,
       4.200e+01, 5.300e+01, 5.300e+01, 6.400e+01, 1.230e+02, 1.230e+02,
       2.130e+02, 2.130e+02, 2.340e+02, 2.340e+02, 4.350e+02, 4.234e+03])

# 2 D Array

In [49]:
a=np.array([[1,9,0,5,3],[4,5,2,7,4]])
a

array([[1, 9, 0, 5, 3],
       [4, 5, 2, 7, 4]])

In [55]:
b=np.array([[7,3,6,8,9],[3,5,8,4,3]])
b
c=np.concatenate((a,b))
c

array([[1, 9, 0, 5, 3],
       [4, 5, 2, 7, 4],
       [7, 3, 6, 8, 9],
       [3, 5, 8, 4, 3]])