In [1]:
import numpy as np


In [13]:
# 3 even array
oned=np.arange(2,13,2)
oned

array([ 2,  4,  6,  8, 10, 12])

In [9]:
# linspace, it is like a range, we need secific numbers of values in a range
np.linspace(1,5,4)


array([1.        , 2.33333333, 3.66666667, 5.        ])

In [38]:
#reshape() is use to tranform dimentions of array

oned=oned.reshape(2,3)
oned

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## Mathematical operations 

In [39]:
arr01=np.arange(1,10).reshape(3,3)
arr02=np.arange(1,10).reshape(3,3)
print(arr01)
print(arr02)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
arr01+arr02

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [41]:
# we can add two matrics using a function

np.add(arr01,arr02)



array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [42]:
# subtraction
arr01-arr02

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
# we can suntract using function
np.subtract(arr01,arr02)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
arr01/arr02

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.divide(arr01,arr02)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.multiply(arr01,arr02)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])