Creating array

In [8]:
import numpy as np
print("1-D ", np.array([1]),'Dimension',np.array([1]).ndim)
print("2-D " ,np.array([[1,2],[1,2]]))
print("3-D ",np.array([[[1,2,3],[1,2,3],[1,2,3]]]))
print("10-D ",np.array([1],ndmin=10))

1-D  [1] Dimension 1
2-D  [[1 2]
 [1 2]]
3-D  [[[1 2 3]
  [1 2 3]
  [1 2 3]]]
10-D  [[[[[[[[[[1]]]]]]]]]]


In [3]:
import numpy as np
x=np.zeros(4)
print(x)

[0. 0. 0. 0.]


In [4]:
import numpy as np
x=np.ones(4)
print(x)

[1. 1. 1. 1.]


In [6]:
import numpy as np
x=np.zeros((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
import numpy as np
x=np.empty(4)
print(x)

[1. 1. 1. 1.]


In [23]:
import numpy as np
# print(np.arrange(4))

In [24]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print(np.linspace(0,20,num=5))

[ 0.  5. 10. 15. 20.]
