In [1]:
import numpy as np
print(np.random.rand(4))

[0.16545986 0.53109959 0.06248455 0.13243131]


In [2]:
print(np.random.randn(4))

[-1.27463407 -1.28252009 -0.43721393 -0.17593113]


In [10]:
print(np.random.randint(0,5,5))

[3 2 4 2 0]
