In [1]:
import numpy as np
l=np.array([1,2])
m=np.array([1,2])
n=np.concatenate((l,m))
print(n)

[1 2 1 2]


In [3]:
l=np.array([[1,2],[3,2]])
m=np.array([[0,7],[4,5]])
n=np.concatenate((l,m))
print(n)

[[1 2]
 [3 2]
 [0 7]
 [4 5]]


In [4]:
l=np.array([[1,2],[3,2]])
m=np.array([[0,7],[4,5]])
n=np.concatenate((l,m),axis=1)
print(n)

[[1 2 0 7]
 [3 2 4 5]]


In [9]:
l=np.array([[1,2],[3,2]])
m=np.array([[0,7],[4,5]])
n=np.stack((l,m))
print(n,"\n")
n=np.hstack((l,m))
print(n,"\n")
n=np.vstack((l,m))
print(n,"\n")
n=np.dstack((l,m))
print(n)

[[[1 2]
  [3 2]]

 [[0 7]
  [4 5]]] 

[[1 2 0 7]
 [3 2 4 5]] 

[[1 2]
 [3 2]
 [0 7]
 [4 5]] 

[[[1 0]
  [2 7]]

 [[3 4]
  [2 5]]]


split

In [25]:
import numpy as np
l=np.array([1,2,3,4,5,6,7,8,9])
x=np.array_split(l,3)
print(x)




[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [29]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array_split(l,3,axis=1)
print(x)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
