In [1]:
import numpy as np
x=np.matrix([[1,2],[2,3]])
print(x)

[[1 2]
 [2 3]]


for multiplication we use dot() function 

In [4]:
x=np.matrix([[1,2],[2,3]])
y=np.matrix([[5,2],[1,3]])
print(x.dot(y))

[[ 7  8]
 [13 13]]


To find Transpose we use ...

In [11]:
x=np.matrix([[1,2],[5,6]])
print(x,"\n")
print(np.transpose(x))
# print(x.T)

[[1 2]
 [5 6]] 

[[1 5]
 [2 6]]


To swapaxis(x,0,1)

In [16]:
x=np.matrix([[1,2],[2,3]])
# print(np.swapaxis(x,0,1))

inverse matrix


In [17]:
x=np.matrix([[1,2],[2,3]])
print(np.linalg.inv(x))

[[-3.  2.]
 [ 2. -1.]]


power

In [19]:
x=np.matrix([[1,2],[2,3]])
print(np.linalg.matrix_power(x,2))
print(np.linalg.matrix_power(x,0))
print(np.linalg.matrix_power(x,-1))

[[ 5  8]
 [ 8 13]]
[[1 0]
 [0 1]]
[[-3.  2.]
 [ 2. -1.]]


deteminant

In [22]:
x=np.matrix([[9,2],[1,3]])
print(np.linalg.det(x))

25.000000000000007
