In [1]:
import numpy as np

print(np.array([1,2,3,4,5,6,7,8,9]))

[1 2 3 4 5 6 7 8 9]


In [15]:
l = np.array([[1,2],[1,2]])
print(l.shape)

(2, 2)


In [17]:
l = np.array([1,2,3,4,5,6,7,8,9])
print(l.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
l = np.array([1,2,3,4,5,6,7,8])
print(l.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]
